version: '2.1'
services:
  prometheus:
    container_name: ${CONTAINER_HOST_NAME:-standalone.prometheus}
    #environment:
    hostname: ${CONTAINER_HOST_NAME:-standalone.prometheus}
    labels:
      deploy.config.commit: ${LABEL_DEPLOY_CONFIG_COMMIT:-unknown}
      deploy.config.name: ${LABEL_DEPLOY_CONFIG_NAME:-unknown}
      deploy.config.ref: ${LABEL_DEPLOY_CONFIG_REF:-unknown}
      deploy.util.commit: ${LABEL_DEPLOY_UTIL_COMMIT:-unknown}
      deploy.util.ref: ${LABEL_DEPLOY_UTIL_REF:-unknown}
      instance.name.short: ${LABEL_INSTANCE_NAME_SHORT:-standalone.prometheus}
      instance.name: ${LABEL_INSTANCE_NAME:-127.0.0.1/prometheus/standalone}
    image: ${IMAGE_PREFIX:-prom/}${IMAGE_NAME:-prometheus}:${IMAGE_TAG:-v2.5.0}
    networks:
      local-network:
        ipv4_address: ${IPV4_ADDRESS:-172.16.238.88}
        #ipv6_address: ${IPV6_ADDRESS:-2001:3984:3989::88}
    ports:
    - "${EXTERNAL_PROMETHEUS_9090_PORT:-9090}:9090"
    restart: always
    volumes:
    - prometheus_data:/prometheus
    - ${PROMETHEUS_CONFIG:-./data/etc/prometheus/prometheus.yml}:/etc/prometheus/prometheus.yml:ro


networks:
  local-network:
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
      #- subnet: 2001:3984:3989::/64


volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data/prometheus
      o: bind
